-- ==============================================================================
--  MANUAL SCHEMA IMPORT (STRICT MATCH)
--  Generated by Antigravity based on exact user specifications.
--  Ordered to satisfy Foreign Key dependencies.
-- ==============================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. HELPER & TRIGGER FUNCTIONS

-- Standard updated_at timestamp function
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- Alias for app_modules if requested specifically
CREATE OR REPLACE FUNCTION public.set_app_module_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- Function to handle new user inputs from Auth (Standard pattern)
CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public.users (id, name, email, role_id)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'name', 'New User'), NEW.email, 'unverified')
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

-- Trigger Overnight Approval (Recovered from backup)
CREATE OR REPLACE FUNCTION public.trigger_overnight_approval()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    last_check_in timestamptz;
    shift_start_hour int;
BEGIN
    IF NEW.type = 'check_out' THEN
        SELECT timestamp INTO last_check_in
        FROM public.attendance_events
        WHERE user_id = NEW.user_id
        AND type = 'check_in'
        AND timestamp < NEW.timestamp
        ORDER BY timestamp DESC
        LIMIT 1;

        IF last_check_in IS NOT NULL THEN
            shift_start_hour := EXTRACT(HOUR FROM last_check_in);
            
            IF shift_start_hour >= 18 OR shift_start_hour < 6 THEN
                 INSERT INTO public.attendance_approvals (user_id, check_in_time, check_out_time, status)
                 VALUES (NEW.user_id, last_check_in, NEW.timestamp, 'pending');
                 
                 INSERT INTO public.notifications (user_id, message, type, link_to)
                 SELECT u.reporting_manager_id, 'Approval required for overnight shift: ' || (SELECT name FROM public.users WHERE id = NEW.user_id), 'info', '/attendance/approvals'
                 FROM public.users u
                 WHERE u.id = NEW.user_id AND u.reporting_manager_id IS NOT NULL;
            END IF;
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

-- Placeholder for handle_user_role_update (Missing from user input)
CREATE OR REPLACE FUNCTION public.handle_user_role_update()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  -- Logic to handle role updates (e.g. logging or notifications) goes here.
  -- Currently empty as definition was not provided.
  RETURN NEW;
END;
$$;


-- 3. TABLES (Ordered)

-- ROLES
CREATE TABLE IF NOT EXISTS public.roles (
  id text NOT NULL,
  display_name text NOT NULL,
  CONSTRAINT roles_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- ORGANIZATION GROUPS
CREATE TABLE IF NOT EXISTS public.organization_groups (
  id text NOT NULL,
  name text NOT NULL,
  CONSTRAINT organization_groups_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- ORGANIZATIONS
CREATE TABLE IF NOT EXISTS public.organizations (
  id text NOT NULL,
  short_name text NOT NULL,
  full_name text NOT NULL,
  address text,
  manpower_approved_count integer,
  reporting_manager_name text NULL,
  manager_name text NULL,
  field_officer_names text[] NULL,
  backend_field_officer_names text[] NULL,
  provisional_creation_date timestamp with time zone NULL,
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_organizations_manager ON public.organizations USING btree (manager_name) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_organizations_reporting_manager ON public.organizations USING btree (reporting_manager_name) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_organizations_provisional_date ON public.organizations USING btree (provisional_creation_date) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_organizations_backend_officer ON public.organizations USING btree (backend_field_officer_names) TABLESPACE pg_default;

-- USERS
CREATE TABLE IF NOT EXISTS public.users (
  id uuid NOT NULL,
  name text NOT NULL,
  email text UNIQUE,
  phone text NULL,
  role_id text NOT NULL DEFAULT 'unverified'::text,
  organization_id text NULL,
  organization_name text NULL,
  reporting_manager_id uuid NULL,
  photo_url text NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  updated_at timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_email_key UNIQUE (email),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users (id) ON DELETE CASCADE,
  CONSTRAINT users_reporting_manager_id_fkey FOREIGN KEY (reporting_manager_id) REFERENCES public.users (id) ON DELETE SET NULL,
  CONSTRAINT users_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles (id)
) TABLESPACE pg_default;

CREATE TRIGGER on_public_user_updated
AFTER UPDATE OF role_id ON users
FOR EACH ROW WHEN (old.role_id IS DISTINCT FROM new.role_id)
EXECUTE FUNCTION handle_user_role_update();

-- APP MODULES
CREATE TABLE IF NOT EXISTS public.app_modules (
  id text NOT NULL,
  name text NOT NULL,
  description text NULL,
  permissions text[] NOT NULL DEFAULT '{}'::text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT app_modules_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TRIGGER app_modules_set_updated_at BEFORE UPDATE ON app_modules 
FOR EACH ROW EXECUTE FUNCTION set_app_module_updated_at();

-- LOCATIONS
CREATE TABLE IF NOT EXISTS public.locations (
  id uuid NOT NULL DEFAULT gen_random_uuid (),
  name text NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  radius numeric NOT NULL,
  address text NULL,
  created_by uuid NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT locations_pkey PRIMARY KEY (id),
  CONSTRAINT locations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users (id) ON DELETE SET NULL
) TABLESPACE pg_default;

-- COMPANIES
CREATE TABLE IF NOT EXISTS public.companies (
  id text NOT NULL,
  name text NOT NULL,
  group_id text NULL,
  CONSTRAINT companies_pkey PRIMARY KEY (id),
  CONSTRAINT companies_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.organization_groups (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- ENTITIES
CREATE TABLE IF NOT EXISTS public.entities (
  id text NOT NULL,
  name text NOT NULL,
  organization_id text NULL,
  location text NULL,
  registered_address text NULL,
  registration_type text NULL,
  registration_number text NULL,
  gst_number text NULL,
  pan_number text NULL,
  email text NULL,
  e_shram_number text NULL,
  shop_and_establishment_code text NULL,
  epfo_code text NULL,
  esic_code text NULL,
  psara_license_number text NULL,
  psara_valid_till text NULL,
  company_id text NULL,
  insurance_ids text[] NULL DEFAULT '{}'::text[],
  policy_ids text[] NULL DEFAULT '{}'::text[],
  CONSTRAINT entities_pkey PRIMARY KEY (id),
  CONSTRAINT entities_organization_id_key UNIQUE (organization_id),
  CONSTRAINT entities_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- USER LOCATIONS
CREATE TABLE IF NOT EXISTS public.user_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid (),
  user_id uuid NOT NULL,
  location_id uuid NOT NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT user_locations_pkey PRIMARY KEY (id),
  CONSTRAINT user_locations_location_id_fkey FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE,
  CONSTRAINT user_locations_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- ATTENDANCE EVENTS
CREATE TABLE IF NOT EXISTS public.attendance_events (
  id uuid NOT NULL DEFAULT gen_random_uuid (),
  user_id uuid NOT NULL,
  timestamp timestamp with time zone NOT NULL,
  type text NOT NULL,
  latitude double precision NULL,
  longitude double precision NULL,
  location_id uuid NULL,
  CONSTRAINT attendance_events_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_events_location_id_fkey FOREIGN KEY (location_id) REFERENCES locations (id),
  CONSTRAINT attendance_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE TRIGGER on_check_out_approval
AFTER INSERT ON attendance_events FOR EACH ROW
EXECUTE FUNCTION trigger_overnight_approval();

-- LEAVE REQUESTS
CREATE TABLE IF NOT EXISTS public.leave_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid (),
  user_id uuid NOT NULL,
  leave_type text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  reason text NOT NULL,
  status text NOT NULL,
  day_option text NULL,
  current_approver_id uuid NULL,
  approval_history jsonb NULL,
  doctor_certificate jsonb NULL,
  CONSTRAINT leave_requests_pkey PRIMARY KEY (id),
  CONSTRAINT leave_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- COMP OFF LOGS
CREATE TABLE IF NOT EXISTS public.comp_off_logs (
  id uuid NOT NULL DEFAULT extensions.uuid_generate_v4 (),
  user_id uuid NOT NULL,
  user_name text NULL,
  date_earned date NOT NULL,
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'earned'::text,
  leave_request_id uuid NULL,
  granted_by_id uuid NULL,
  granted_by_name text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT comp_off_logs_pkey PRIMARY KEY (id),
  CONSTRAINT comp_off_logs_granted_by_id_fkey FOREIGN KEY (granted_by_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT comp_off_logs_leave_request_id_fkey FOREIGN KEY (leave_request_id) REFERENCES leave_requests (id) ON DELETE SET NULL,
  CONSTRAINT comp_off_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT comp_off_logs_status_check CHECK ((status = ANY (array['earned'::text, 'used'::text, 'expired'::text])))
) TABLESPACE pg_default;

-- EXTRA WORK LOGS
CREATE TABLE IF NOT EXISTS public.extra_work_logs (
  id uuid NOT NULL DEFAULT extensions.uuid_generate_v4 (),
  user_id uuid NOT NULL,
  user_name text NULL,
  work_date date NOT NULL,
  work_type text NOT NULL,
  claim_type text NOT NULL,
  hours_worked numeric NULL,
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'Pending'::text,
  approver_id uuid NULL,
  approver_name text NULL,
  approved_at timestamp with time zone NULL,
  rejection_reason text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT extra_work_logs_pkey PRIMARY KEY (id),
  CONSTRAINT extra_work_logs_approver_id_fkey FOREIGN KEY (approver_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT extra_work_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT extra_work_logs_claim_type_check CHECK ((claim_type = ANY (array['OT'::text, 'Comp Off'::text]))),
  CONSTRAINT extra_work_logs_status_check CHECK ((status = ANY (array['Pending'::text, 'Approved'::text, 'Rejected'::text]))),
  CONSTRAINT extra_work_logs_work_type_check CHECK ((work_type = ANY (array['Holiday'::text, 'Week Off'::text, 'Night Shift'::text])))
) TABLESPACE pg_default;

-- ATTENDANCE APPROVALS
CREATE TABLE IF NOT EXISTS public.attendance_approvals (
  id uuid NOT NULL DEFAULT gen_random_uuid (),
  user_id uuid NOT NULL,
  check_in_time timestamp with time zone NOT NULL,
  check_out_time timestamp with time zone NULL,
  status text NOT NULL,
  manager_id uuid NULL,
  rejection_reason text NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  updated_at timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT attendance_approvals_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_approvals_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES users (id),
  CONSTRAINT attendance_approvals_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT attendance_approvals_status_check CHECK ((status = ANY (array['pending'::text, 'approved'::text, 'rejected'::text])))
) TABLESPACE pg_default;

-- SUPPORT TICKETS
CREATE TABLE IF NOT EXISTS public.support_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid (),
  ticket_number text NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  category text NOT NULL,
  priority text NOT NULL,
  status text NOT NULL,
  raised_by_id uuid NOT NULL,
  raised_by_name text NOT NULL,
  raised_at timestamp with time zone NULL DEFAULT now(),
  assigned_to_id uuid NULL,
  assigned_to_name text NULL,
  resolved_at timestamp with time zone NULL,
  closed_at timestamp with time zone NULL,
  rating integer NULL,
  feedback text NULL,
  posts jsonb NULL DEFAULT '[]'::jsonb,
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_ticket_number_key UNIQUE (ticket_number),
  CONSTRAINT support_tickets_assigned_to_id_fkey FOREIGN KEY (assigned_to_id) REFERENCES users (id),
  CONSTRAINT support_tickets_raised_by_id_fkey FOREIGN KEY (raised_by_id) REFERENCES users (id)
) TABLESPACE pg_default;

-- TICKET POSTS
CREATE TABLE IF NOT EXISTS public.ticket_posts (
  id uuid NOT NULL DEFAULT extensions.uuid_generate_v4 (),
  ticket_id uuid NOT NULL,
  author_id uuid NULL,
  author_name text NULL,
  author_role text NULL,
  content text NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  likes uuid[] NULL DEFAULT array[]::uuid[],
  CONSTRAINT ticket_posts_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT ticket_posts_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES support_tickets (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- TICKET COMMENTS
CREATE TABLE IF NOT EXISTS public.ticket_comments (
  id uuid NOT NULL DEFAULT extensions.uuid_generate_v4 (),
  post_id uuid NOT NULL,
  author_id uuid NULL,
  author_name text NULL,
  content text NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT ticket_comments_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT ticket_comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES ticket_posts (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- TASKS
CREATE TABLE IF NOT EXISTS public.tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid (),
  name text NOT NULL,
  description text NULL,
  due_date date NULL,
  priority text NOT NULL,
  status text NOT NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  created_by_id uuid NULL,
  assigned_to_id uuid NULL,
  completion_notes text NULL,
  completion_photo jsonb NULL,
  escalation_status text NULL,
  escalation_level1_user_id uuid NULL,
  escalation_level1_duration_days integer NULL,
  escalation_level2_user_id uuid NULL,
  escalation_level2_duration_days integer NULL,
  escalation_email text NULL,
  escalation_email_duration_days integer NULL,
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_assigned_to_id_fkey FOREIGN KEY (assigned_to_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT tasks_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL
) TABLESPACE pg_default;

-- NOTIFICATIONS
CREATE TABLE IF NOT EXISTS public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid (),
  user_id uuid NOT NULL,
  message text NOT NULL,
  type text NOT NULL,
  is_read boolean NULL DEFAULT false,
  created_at timestamp with time zone NULL DEFAULT now(),
  link_to text NULL,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- ONBOARDING SUBMISSIONS
CREATE TABLE IF NOT EXISTS public.onboarding_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid (),
  employee_id text NULL,
  status text NOT NULL,
  portal_sync_status text NULL,
  organization_id text NULL,
  organization_name text NULL,
  enrollment_date date NOT NULL,
  requires_manual_verification boolean NULL DEFAULT false,
  forms_generated boolean NULL DEFAULT false,
  created_user_id uuid NULL,
  user_id uuid NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  updated_at timestamp with time zone NULL DEFAULT now(),
  personal jsonb NULL,
  address jsonb NULL,
  family jsonb NULL,
  education jsonb NULL,
  bank jsonb NULL,
  uan jsonb NULL,
  esi jsonb NULL,
  gmc jsonb NULL,
  organization jsonb NULL,
  uniforms jsonb NULL,
  biometrics jsonb NULL,
  salary_change_request jsonb NULL,
  verification_usage jsonb NULL,
  CONSTRAINT onboarding_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT onboarding_submissions_created_user_id_key UNIQUE (created_user_id),
  CONSTRAINT onboarding_submissions_employee_id_key UNIQUE (employee_id),
  CONSTRAINT onboarding_submissions_created_user_id_fkey FOREIGN KEY (created_user_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT onboarding_submissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_onboarding_organization_id ON public.onboarding_submissions USING btree (organization_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_onboarding_status ON public.onboarding_submissions USING btree (status) TABLESPACE pg_default;

-- INDEPENDENT TABLES
CREATE TABLE IF NOT EXISTS public.holidays (
  id uuid NOT NULL DEFAULT gen_random_uuid (),
  date date NOT NULL,
  name text NOT NULL,
  type text NULL,
  CONSTRAINT holidays_pkey PRIMARY KEY (id),
  CONSTRAINT holidays_date_key UNIQUE (date),
  CONSTRAINT holidays_type_check CHECK ((type = ANY (array['office'::text, 'field'::text])))
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.insurances (
  id uuid NOT NULL DEFAULT gen_random_uuid (),
  type text NOT NULL,
  provider text NOT NULL,
  policy_number text NOT NULL,
  valid_till date NOT NULL,
  CONSTRAINT insurances_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.location_cache (
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  address text NOT NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT location_cache_pkey PRIMARY KEY (latitude, longitude)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.policies (
  id uuid NOT NULL DEFAULT gen_random_uuid (),
  name text NOT NULL,
  description text NULL,
  CONSTRAINT policies_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.recurring_holidays (
  id uuid NOT NULL DEFAULT gen_random_uuid (),
  role_type text NOT NULL,
  day text NOT NULL,
  occurrence integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone ('utc'::text, now()),
  CONSTRAINT recurring_holidays_pkey PRIMARY KEY (id),
  CONSTRAINT recurring_holidays_role_type_check CHECK ((role_type = ANY (array['office'::text, 'field'::text])))
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.settings (
  id text NOT NULL DEFAULT 'singleton'::text,
  attendance_settings jsonb NULL,
  gmc_policy jsonb NULL,
  enrollment_rules jsonb NULL,
  api_settings jsonb NULL,
  verification_costs jsonb NULL,
  back_office_id_series jsonb NULL,
  site_staff_designations jsonb NULL,
  master_tools jsonb NULL,
  master_gents_uniforms jsonb NULL,
  master_ladies_uniforms jsonb NULL,
  approval_workflow_settings jsonb NULL,
  CONSTRAINT settings_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.site_configurations (
  id uuid NOT NULL DEFAULT gen_random_uuid (),
  organization_id text NOT NULL,
  config_data jsonb NULL,
  CONSTRAINT site_configurations_pkey PRIMARY KEY (id),
  CONSTRAINT site_configurations_organization_id_key UNIQUE (organization_id)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.site_gents_uniform_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid (),
  organization_id text NOT NULL,
  config_data jsonb NULL,
  CONSTRAINT site_gents_uniform_configs_pkey PRIMARY KEY (id),
  CONSTRAINT site_gents_uniform_configs_organization_id_key UNIQUE (organization_id)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.site_ladies_uniform_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid (),
  organization_id text NOT NULL,
  config_data jsonb NULL,
  CONSTRAINT site_ladies_uniform_configs_pkey PRIMARY KEY (id),
  CONSTRAINT site_ladies_uniform_configs_organization_id_key UNIQUE (organization_id)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.site_staff_designations (
  id uuid NOT NULL DEFAULT gen_random_uuid (),
  department text NOT NULL,
  designation text NOT NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT site_staff_designations_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.site_uniform_details_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid (),
  organization_id text NOT NULL,
  config_data jsonb NULL,
  CONSTRAINT site_uniform_details_configs_pkey PRIMARY KEY (id),
  CONSTRAINT site_uniform_details_configs_organization_id_key UNIQUE (organization_id)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.uniform_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid (),
  site_id text NOT NULL,
  site_name text NOT NULL,
  gender text NOT NULL,
  requested_date timestamp with time zone NOT NULL,
  status text NOT NULL,
  items jsonb NULL,
  source text NULL,
  requested_by_id uuid NULL,
  requested_by_name text NULL,
  employee_details jsonb NULL,
  CONSTRAINT uniform_requests_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- STORAGE
insert into storage.buckets (id, name, public)
values 
  ('documents', 'documents', false),
  ('photos', 'photos', false)
on conflict (id) do nothing;

DROP POLICY IF EXISTS "Authenticated users can upload documents" ON storage.objects;
create policy "Authenticated users can upload documents"
  on storage.objects for insert
  with check (bucket_id = 'documents' and auth.role() = 'authenticated');

-- REALTIME
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
  
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.attendance_events;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;

  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.onboarding_submissions;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
END $$;

-- AUTH TRIGGER
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();

